project_id = "opzsrqdvotozawuqpapo"



[functions.generate-ad]
verify_jwt = false

[functions.generate-product-images]
verify_jwt = false

[functions.parse-bank-statement]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.asaas-checkout]
enabled = true
verify_jwt = true
entrypoint = "./functions/asaas-checkout/index.ts"

[functions.asaas-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/asaas-webhook/index.ts"

[functions.asaas-cancel]
enabled = true
verify_jwt = true
entrypoint = "./functions/asaas-cancel/index.ts"
